### ISSUE TITLE
Upgrade Unity Project to 2022.3.32f1 Version

### ISSUE THREAD

**Issue by ShubhamGawande191** [HBRS-SDP/ss24-reinforcement-learning-simulator#4]
- Test and fix any compatibility issues that arise from upgrades
- Deliverables: Updated Unity project files, updated documentation
- Resolve any compatibility issues, such as deprecated APIs or assets
- Test the project thoroughly to ensure that simulations and graphics render correctly
- Document differences between the current and new versions to inform testing

**Comment by ShubhamGawande191** [comment]
Known bugs:
- Script compilation errors
- Older .meta files in the Unity Assets folder causing compilation errors
- Avatar missing UpperLeg file

**Comment by ShubhamGawande191** [comment]
> Known bugs:
> 
> * Script compilation errors
> * Older .meta files in the Unity Assets folder causing compilation errors
> * Avatar missing UpperLeg file

Bugs fixed:

- [x] Script compilation errors - Made a few changes to scripts with issues

- [x] Older .meta files in the Unity Assets folder causing compilation errors - removed all the .meta files and reimported all scripts after which we copied the missing ".meta" files

- [x] Avatar missing UpperLeg file

**Comment by Jobecho91** [comment]
### Issue with PathTracer and Mesh Geometry in Unity.

- Description: 
The error occurs when the PathTracer fails to add geometry for a specific mesh due to non-finite values in the texture coordinates.

- Solution:
Disabling the "Auto Generate" option in the Lighting settings prevented automatic generation of lighting, allowing for manual control and verification of mesh data before generating lighting.

- Steps to Resolve:
Go to Window > Rendering > Lighting and uncheck the "Auto Generate" option.
